name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check login file
        run: |
          if [ ! -f "dashboard.php" ]; then
            echo "dashboard.php not found!"
            exit 1
          fi
